import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

import { Providers } from "./providers";
import ProviderCart from "@/Providers/CartProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export interface NavLink {
  name: string;
  href: string;
}

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: any
}) {
  const navLinks: NavLink[] = [
    {
      name: "iPhones",
      href: "/shop/iphone",
    },
    {
      name: "Androids",
      href: "/shop/android",
    },
    {
      name: "Smartwatchs",
      href: "/shop/smartwatch",
    },
    {
      name: "Fones Bluetooth",
      href: "/shop/fone",
    },
    {
      name: "Black Friday",
      href: "/shop/blackfriday",
    },
  ];

  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderCart>
          <Header navLinks={navLinks} />
          <Providers>
            {children} {modal}
          </Providers>
          <Footer />
        </ProviderCart>
      </body>
    </html>
  );
}
