import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export interface NavLink {
  name: string;
  href: string;
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const navLinks: NavLink[] = [
    {
      name: "iPhones",
      href: "/products/iphone",
    },
    {
      name: "Androids",
      href: "/products/android",
    },
    {
      name: "Smartwatchs",
      href: "/products/smartwatch",
    },
    {
      name: "Fones Bluetooth",
      href: "/products/fone",
    },
    {
      name: "Black Friday",
      href: "/products/blackfriday",
    },
  ];

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header navLinks={navLinks} />
        {children}
      </body>
    </html>
  );
}
