import type { Metadata } from "next";

import { Inter } from "next/font/google";

import LayoutAdmin from "@/components/AdminLayout";

import "../../styles/globals.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export interface NavLink {
  name: string;
  href: string;
}

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const navLinks: NavLink[] = [
    {
      name: "Produtos",
      href: "/admin/products",
    },
    {
      name: "Estoque",
      href: "/admin/stocks",
    },
    {
      name: "Cor",
      href: "/admin/colors",
    },
    {
      name: "Armazenamento",
      href: "/admin/storages",
    },
    {
      name: "Categoria",
      href: "/admin/categories",
    },
    {
      name: "Pedidos",
      href: "/admin/orders",
    },
    {
      name: "Novidades",
      href: "/admin/news",
    },
    {
      name: "Oferta Black Friday",
      href: "/admin/blackfriday",
    },
  ];

  return (
    <html lang="en">
      <body className={`${inter.className} flex justify-center gap-20 py-8 `}>
        <LayoutAdmin navLinks={navLinks} />
        {children}
      </body>
    </html>
  );
}
